export const INITIALIZE_START = 'INITIALIZE_START';
export const INITIALIZE_END = 'INITIALIZE_END';
export const SEARCH_USER = 'SEARCH_USER';
export const GET_REPOS = 'GET_REPOS';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';
